conda-forge/jina-hubble-sdk-feedstock

recipe/meta.yaml

fix: upgrade the version to 0.2.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.2.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.2.3 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.2.4 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.2.5 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.3.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.4.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.5.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.5.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.5.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.6.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.6.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.6.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.6.3 in file meta.yaml

---

recipe/meta.yaml

 fix: upgrade the version to 0.6.4 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.6.5 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.7.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.9.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.9.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.9.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.11.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.12.0 in file meta.yaml

---

recipe/meta.yaml

 fix: upgrade the version to 0.12.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.12.3 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.12.5 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.14.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.15.6 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.16.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.19.3 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.20.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.20.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.22.0 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.22.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.22.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.22.3 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.22.4 in file meta.yaml

---

recipe/meta.yaml

 fix: upgrade the version to 0.22.5 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.23.1 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.23.2 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.23.3 in file meta.yaml

---

recipe/meta.yaml

fix: upgrade the version to 0.24.0 in file meta.yaml (#1)
